server:
  port: 8083
spring:
  application:
    name: search-service
  elasticsearch:
    rest:
      uris:
        - http://192.168.153.137:9200
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    root: info
    com.ego.sear: debug
